const rules = [
  { id: "CREATE", pattern: /^CREATE/i },
  { id: "DATABASE", pattern: /^DATABASE/i },
  { id: "TABLE", pattern: /^TABLE/i },
  { id: "SELECT", pattern: /^SELECT/i },
  { id: "DROP", pattern: /^DROP/i },
  { id: "INSERT", pattern: /^INSERT/i },
  { id: "INTO", pattern: /^INTO/i },
  { id: "VALUES", pattern: /^VALUES/i },
  { id: "FROM", pattern: /^FROM/i },
  { id: "WHERE", pattern: /^WHERE/i },
  { id: "STRING", pattern: /^("|').*("|')/ },
  { id: "SEMICOLON", pattern: /^;/ },
  { id: "LEFT_PARENTHESIS", pattern: /^\(/ },
  { id: "RIGHT_PARENTHESIS", pattern: /^\)/ },
  { id: "VARCHAR", pattern: /^VARCHAR/i },
  { id: "INT", pattern: /^INT/i },
  { id: "DIGIT", pattern: /^[0-9]/ },
  { id: "DIGITS", pattern: /^[0-9]+/ },
  { id: "COMMA", pattern: /^,/ },
  { id: "NUMBER", pattern: /^[0-9]+(\.[0-9]+)?/ },
  { id: "ASTERISK", pattern: /^\*/ },
  { id: "EQUALS", pattern: /^==/ },
  { id: "LESS_THAN", pattern: /^</ },
  { id: "MORE_THAN", pattern: /^>/ },
  { id: "LESS_THAN_EQUALS", pattern: /^<=/ },
  { id: "MORE_THAN_EQUALS", pattern: /^>=/ },
  { id: "NOT_EQUAL", pattern: /^!=/ },
  { id: "IDENTIFIER", pattern: /^[a-zA-Z_]+/ },
];

module.exports = {
  rules,
};
